apiVersion: apps/v1
kind: Deployment
metadata:
  name: runningpocui-deployment
spec:
  selector:
    matchLabels:
      app: runningpocui-pod
  template:
    metadata:
      labels:
        app: runningpocui-pod
    spec:
      containers:
      - name: runningpocui-container
        image: ipascontreg.azurecr.io/runningpocui:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
